-- TT 2006-10-09: drop table jbb_answer_notify
DROP TABLE jbb_answer_notify;
DROP TABLE jbb_badwords;
DROP TABLE jbb_category;
DROP TABLE jbb_forum;
-- TT 2006-10-09: drop table jbb_forum_top_user
DROP TABLE jbb_forum_top_user;
DROP TABLE jbb_posts;
DROP TABLE jbb_privmsg_inbox;
DROP TABLE jbb_privmsg_outbox;
DROP TABLE jbb_smiles;
DROP TABLE jbb_topics;
DROP TABLE jbb_users;

-- TT 2006-10-09: create table jbb_answer_notify
CREATE TABLE jbb_answer_notify (
 id_topic bigint default '0' NOT NULL,
 id_user bigint default '0' NOT NULL,
 PRIMARY KEY  (id_topic,id_user)
);
--KEY jbb_answer_notify_ind1_fk (id_topic),
--KEY jbb_answer_notify_ind2_fk (id_user),
--KEY JBB_ANSWER_NOTIFY_FK (id_topic),
--KEY JBB_ANSWER_NOTIFYIDEX_FK (id_user)


CREATE TABLE jbb_badwords (
 id_badword bigint NOT NULL PRIMARY KEY,
 word varchar(50) NULL,
 replacement varchar(50) NULL
);

CREATE TABLE jbb_category (
 id_category bigint NOT NULL PRIMARY KEY,
 nm_category varchar(200) NULL,
 cat_order int default '0' NOT NULL
);

CREATE TABLE jbb_forum (
 id_forum bigint NOT NULL PRIMARY KEY,
 nome varchar(200) NULL,
 descricao varchar(200) NULL,
 forum_status int NULL,
 forum_order int NULL,
 id_category bigint default '0' NOT NULL,
 last_post_id bigint default NULL,
 topic_count bigint default NULL,
 post_count bigint default NULL,
 last_page_post bigint default '1',
 last_post_user_name varchar(255) default NULL,
 last_post_user_id bigint default NULL,
 last_post_date timestamp NOT NULL,
 last_topic_id bigint default NULL
);

-- TT 2006-10-09: create table jbb_forum_top_user
CREATE TABLE jbb_forum_top_user (
 id_user int default '0' NOT NULL,
 post_count int default '0' NOT NULL,
 date_row timestamp default CURRENT_TIMESTAMP NOT NULL,
 id_forum int default NULL
);
--date_row timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
--KEY id_user (id_user),
--KEY id_forum (`id_forum`)

-- TT 2006-10-09: remove post_body, create jbb_posts_text instead
CREATE TABLE jbb_posts (
 id_post bigint NOT NULL PRIMARY KEY,
 id_user bigint default '0' NOT NULL,
 id_topic bigint default '0' NOT NULL,
 data_post timestamp NOT NULL,
 assunto varchar(200) default NULL,
--post_body longvarchar,
 sig int default '0',
 ip varchar(20) default NULL,
 post_state int default '0'
);

-- TT 2006-10-09: create jbb_posts_text
CREATE TABLE jbb_posts_text (
 id_post bigint default '0' NOT NULL PRIMARY KEY,
 post_body longvarchar
);

CREATE TABLE jbb_privmsg_inbox (
 id_privmsg int NOT NULL PRIMARY KEY,
 id_user_from int default '0' NOT NULL,
 id_user_to int default '0' NOT NULL,
 privmsg_topic varchar(255) default '' NOT NULL,
 privmsg_text longvarchar NOT NULL,
 privmsg_date timestamp NOT NULL,
 allow_bbcode int default '0',
 allow_smiles int default '0',
 attach_sign int default '1',
 flag_read int default '0'
);

CREATE TABLE jbb_privmsg_outbox (
 id_privmsg int NOT NULL PRIMARY KEY,
 id_user_from int default '0' NOT NULL,
 id_user_to int default '0' NOT NULL,
 privmsg_topic varchar(255) default '' NOT NULL,
 privmsg_text longvarchar NOT NULL,
 privmsg_date timestamp NOT NULL,
 allow_bbcode int default '0',
 allow_smiles int default '0',
 attach_sign int default '1',
 flag_read int default '0'
);

-- TT 2006-10-09: create jbb_rank table, change autoincrement
CREATE TABLE jbb_rank (
--rank_id int NOT NULL auto_increment PRIMARY KEY,
 rank_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
 rank_name varchar(255) default NULL,
 rank_min int default NULL,
 rank_max int default NULL,
 rank_image varchar(255) default NULL
);

CREATE TABLE jbb_smiles (
 id bigint NOT NULL PRIMARY KEY,
 symbol varchar(50) default '' NOT NULL,
 emoticon varchar(75) default '' NOT NULL,
 filename varchar(100) default '' NOT NULL
);

CREATE TABLE jbb_topics (
 id_topic bigint NOT NULL PRIMARY KEY,
 id_user bigint default '0' NOT NULL,
 id_forum bigint default '0' NOT NULL,
 title_topic varchar(200) default '' NOT NULL,
 data_topico timestamp NOT NULL,
 visualizacoes int default '0',
 respostas int default '0',
 topic_status int default '0',
 topic_model tinyint default '0',
 last_post_date timestamp NOT NULL,
 last_post_id bigint default NULL,
 last_post_page tinyint default NULL,
 last_post_user_id bigint default NULL,
 last_post_user_name varchar(200) default NULL,
 notify_me tinyint default 0
);

-- TT 2006-10-09: add hash_fpwd column
CREATE TABLE jbb_users (
 id_user bigint NOT NULL PRIMARY KEY,
 user_name varchar(50) default NULL,
 pws varchar(50) default NULL,
 name varchar(100) default NULL,
 email varchar(100) default NULL,
 posts int default '0',
 admin int default '0',
 data_registro timestamp NOT NULL,
 localizacao varchar(100) default NULL,
 website varchar(200) default NULL,
 occupation varchar(200) default NULL,
 user_sig longvarchar,
 user_msnm varchar(200) default NULL,
 user_actualvisit timestamp NOT NULL,
 user_lastvisit timestamp NOT NULL,
 user_dateformat varchar(50) default NULL,
 user_allow_viewonline int default NULL,
 user_avatar varchar(200) default NULL,
 user_icq varchar(50) default NULL,
 user_interests varchar(200) default NULL,
 user_aim varchar(200) default NULL,
 user_yim varchar(200) default NULL,
 show_mail int default '0',
 show_signature int default '0',
 user_status int default NULL,
 user_code varchar(100) default NULL,
 hash_fpwd varchar(100) default NULL
);

-- TT 2006-10-09: create table jbb_fav_topic
CREATE TABLE jbb_fav_topic (
 id_topic bigint default '0' NOT NULL,
 id_user bigint default '0' NOT NULL,
 PRIMARY KEY (id_topic,id_user)
);

INSERT INTO jbb_badwords (id_badword, word, replacement) VALUES (1,'shit','***');

INSERT INTO jbb_category (id_category, nm_category, cat_order)
 VALUES (2,'Misc',30);

INSERT INTO jbb_forum (id_forum, nome, descricao, forum_status, forum_order, id_category, last_post_id, topic_count, post_count, last_page_post, last_post_user_name, last_post_user_id, last_post_date, last_topic_id)
 VALUES (1,'JavaBB Informations','Informations about JavaBB',0,1,2,2,1,1,1,'admin',63,'2005-03-31 20:37:07',NULL);

-- TT 2006-10-09: insert values:
INSERT INTO jbb_forum_top_user (id_user, post_count, date_row, id_forum) VALUES
 (63,3,'2006-04-08 10:51:00',1);

-- TT 2006-10-09: drop post_body column
--INSERT INTO jbb_posts (id_post, id_user, id_topic, data_post, assunto, post_body, sig, ip, post_state)
--  VALUES (2,63,2,'2005-03-31 20:37:07','Informations','Hello user of JavaBB, thanks to you for download our software ;)
INSERT INTO jbb_posts (id_post, id_user, id_topic, data_post, assunto, sig, ip, post_state) VALUES
 ('2','63','2','2005-03-31 20:37:07','Informations',1,NULL,0);
INSERT INTO jbb_posts (id_post, id_user, id_topic, data_post, assunto, sig, ip, post_state) VALUES
 ('3','63','3','2005-06-28 00:19:48','Themes and Buttons in your language',0,NULL,0);
INSERT INTO jbb_posts (id_post, id_user, id_topic, data_post, assunto, sig, ip, post_state) VALUES
 ('4','63','4','2006-04-08 10:04:52','Support of JavaBB',1,NULL,0);

-- TT 2006-10-09: populate jbb_posts_text
INSERT INTO jbb_posts_text (id_post, post_body) VALUES
 (2,'Hello user of JavaBB, thanks to you for download our software ;)\r\n\r\n\r\n[quote]\r\n\r\n[b]Administration info:[/b]\r\n\r\nUser: admin\r\nPassword: admin\r\n\r\n[/quote]\r\n\r\n[b]Attention:[/b]\r\n\r\nThis is version 0.73 of our project.\r\n\r\nSupported features\r\n\r\n[list]\r\n[*] Flood Control\r\n[*] Watch Topic\r\n[*] Config file for custom changes\r\n[*] Complete layout changes thru css-theme files\r\n[*] Languages files and buttons file, based on phpBB\r\n[*] Forum category\r\n[*] Links to other urls\r\n[*] Sticky posts and announcements\r\n[*] BBcode\r\n[*] Locked threads\r\n[*] IP logging system\r\n[*] Paginsystem\r\n[*] Memberregistration and editing\r\n[*] MemberList\r\n[*] Private message system\r\n[*] Adminsystem\r\n[*] Badwordfilter\r\n[*] And much more...\r\n\r\n[/list]\r\n\r\n[url=http://www.javabb.org]JavaBB.Org[/url]');
INSERT INTO jbb_posts_text (id_post, post_body) VALUES
 (3,'Hi all!\r\n\r\nTo translate the buttons, you can download the german buttons at phpbb site ( http://www.phpbb.com/downloads.php ), and copy to folder:\r\n[code]\r\njavabb/forum/images/buttons/${portuguese-Brazilian-Folder}/\r\n[/code]\r\nlike it: https://javabb.dev.java.net/source/browse/javabb/forum/images/buttons/\r\n\r\nAt admin painel(General Config), these files are showed to you, you must select one and modify.\r\n\r\n\r\nTo change the jb2 theme, you must to create a new folder-theme (like jb2, I suggest copy and past jb2 and change the name.).\r\nYou can modify the css, images and all others velocity themes. But you have to change the javabb configuration file in:\r\n\r\n[code]javabb/appconf/javabb.properties[/code]\r\n\r\nThis file can be found here:\r\nhttps://javabb.dev.java.net/source/browse/javabb/appconf/javabb.properties?view=markup\r\n\r\nChange the property \r\n\r\n[code]config.forum.theme=jb2[/code]\r\n\r\nto you theme folder name, like it:\r\n\r\n[code]config.forum.theme=brazilianTheme[/code]\r\n\r\n\r\n[url=http://www.javabb.org]JavaBB.Org[/url]');
INSERT INTO jbb_posts_text (id_post, post_body) VALUES
 (4,'Please, if you have some question or suggest to us, use our group in\r\n\r\n\r\n[quote]\r\n[img]http://groups.google.com/groups/img/groups_medium.gif[/img]\r\nhttp://groups.google.com/group/javabb/\r\n\r\n[/quote]\r\n\r\n\r\nImportant: We dont have much time to spend in this project, then if you help something to suggest or module of codes, this will be welcome.\r\n\r\nThanks,\r\n\r\n[url=http://www.javabb.org]JavaBB.Org[/url]');

INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (2,':-D','Very Happy','icon_biggrin.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (3,':grin:','Very Happy','icon_biggrin.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (4,':)','Smile','icon_smile.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (5,':-)','Smile','icon_smile.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (6,':smile:','Smile','icon_smile.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (7,':(','Sad','icon_sad.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (8,':-(','Sad','icon_sad.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (9,':sad:','Sad','icon_sad.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (10,':o','Metal Rules!!','icon_surprised.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (13,':shock:','Shocked','icon_eek.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (14,':?','Confused','icon_confused.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (15,':-?','Confused','icon_confused.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (16,':???:','Confused','icon_confused.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (17,'8)','Cool','icon_cool.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (18,'8-)','Cool','icon_cool.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (19,':cool:','Cool','icon_cool.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (20,':lol:','Laughing','icon_lol.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (21,':x','Mad','icon_mad.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (22,':-x','Mad','icon_mad.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (23,':mad:','Mad','icon_mad.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (24,':P','Razz','icon_razz.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (25,':-P','Razz','icon_razz.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (26,':razz:','Razz','icon_razz.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (27,':oops:','Embarassed','icon_redface.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (28,':cry:','Crying or Very sad','icon_cry.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (29,':evil:','Evil or Very Mad','icon_evil.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (30,':twisted:','Twisted Evil','icon_twisted.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (31,':roll:','Rolling Eyes','icon_rolleyes.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (32,':wink:','Wink','icon_wink.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (33,';)','Wink','icon_wink.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (34,';-)','Wink','icon_wink.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (35,':!:','Exclamation','icon_exclaim.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (36,':?:','Question','icon_question.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (37,':idea:','Idea','icon_idea.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (38,':arrow:','Arrow','icon_arrow.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (39,':|','Neutral','icon_neutral.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (40,':-|','Neutral','icon_neutral.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (41,':neutral:','Neutral','icon_neutral.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (42,':mrgreen:','Mr. Green','icon_mrgreen.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (43,':(:','Desapontado','icon_disappointed.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (44,':metal:','Ohhh yahh!!!','rockdevil.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (45,':hauhau:','Chorando de rir','hauhau.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (46,':pray:','Rezando','pray.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (47,':getout:','Dando o fora','get_out.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (48,':tantan:','tan-tan','tantan.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (49,':amigos:','Amigos','amigos.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (50,':bebado:','','new_all_coholic.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (51,':espanto:','Espanto','whoa.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (52,':zoio:','Nuuuussaa!!!!','icon_zoiudo.gif');
INSERT INTO jbb_smiles (id, symbol, emoticon, filename) VALUES (53,':P','Razz','icon_razz.gif');

INSERT INTO jbb_topics (id_topic, id_user, id_forum, title_topic, data_topico, visualizacoes, respostas, topic_status, topic_model, last_post_date, last_post_id, last_post_page, last_post_user_id, last_post_user_name)
 VALUES (2,63,1,'Informations','2005-03-31 20:37:07',0,0,0,0,'2005-04-01 17:49:07',NULL,NULL,NULL,NULL);

INSERT INTO jbb_users (id_user, user_name, pws, name, email, posts, admin, data_registro, localizacao, website, occupation, user_sig, user_msnm, user_actualvisit, user_lastvisit, user_dateformat, user_allow_viewonline, user_avatar, user_icq, user_interests, user_aim, user_yim, show_mail, show_signature, user_status, user_code)
 VALUES (1,'Anonymous','','Anonymous','admin@admin.com.br',0,0,'2005-04-05 14:46:36','','','','','','2005-04-08 17:44:13','2005-04-08 17:44:13','D M d, Y g:i a',1,'http://www.javafree.com.br/forum/images/avatars/blank.gif','','','','',0,0,NULL,'f99891a27b384cfcb66e51e4b4dfc667');
INSERT INTO jbb_users (id_user, user_name, pws, name, email, posts, admin, data_registro, localizacao, website, occupation, user_sig, user_msnm, user_actualvisit, user_lastvisit, user_dateformat, user_allow_viewonline, user_avatar, user_icq, user_interests, user_aim, user_yim, show_mail, show_signature, user_status, user_code)
 VALUES (63,'admin','21232f297a57a5a743894a0e4a801fc3','asfda','admin@javabb.org',1,1,'2005-04-08 17:44:13','','','','','','2005-05-24 18:37:29','2005-03-31 20:35:03',NULL,NULL,'','324234','','33','',1,1,NULL,'0e49f4740fb600a158848cee6b84f9f1');